name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-pr-review:
    uses: Open-Paws-Automations/.github/workflows/ai-pr-review.yml@thekaailashsharma-patch-1
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
